# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_EMP',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_num', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='emp num')),
                ('email_address', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('emp_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='emp name')),
                ('admin_flag', models.CharField(default=0, max_length=1, verbose_name='admin flag')),
                ('regist_emp_num', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='regist emp num')),
                ('update_emp_num', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='update emp num')),
                ('regist_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='regist time')),
                ('update_time', models.DateField(default=django.utils.timezone.now, verbose_name='update time')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_emp',
            },
        ),
    ]
